# Welcome to Jekyll!

# Website settings
title: "Abdul Hamid Rather"
description: "Personal website of Abdul Hamid Rather"
keywords: "mrastgoo,mojdeh,rastgoo,medical,imaging,vision,melanoma,polarized,multispectral"
baseurl: ""
url: "https://abrather.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Rather'
  first_name: 'Hamid'
  last_name: 'Rather'
  email: 'rhaamid24@gmail.com'
  linkedin_username: ''
  scholar_username: ''
  github_username: ''
  instagram_username: ''
  head_img: 'static/img/landing/abrather.jpeg'
  intro: "Hey there! I am Rather Hamid, a graduate student, aerospace engineer, and researcher from Germany."
  position: "MS Student @ Universität Bremen"
  desc: >
    I am pursuing a Master of Science (MS) with a concentration in the design, integration, and analysis 
    of aerospace systems at Universität Bremen and hold a Bachelor of Science in Aerospace Engineering. 
    I am currently a Student Researcher in the Fiber, composites & cryogenics lab. In this role, I design 
    and integrate test equipment for cryogenic materials, and crucially, I also develop and automate the 
    data analysis pipelines for these experiments. I use Python, Pandas, Plotly, other libraries and PowerBI 
    to process, analyze, and visualize the test results, turning raw sensor data into actionable insights 
    for material selection.
  sports: "Camping, Volleyball, and Fitness"
  hobbies: "Reading technical papers and exploring new technologies"
  experience: >
    My current work as a Student Researcher at Faserinstitut Bremen is focused on materials for 
    next-generation propulsion. I am designing and building test stands to analyze how composite materials 
    and adhesives behave in cryogenic environments, specifically for hydrogen fuel tanks. This role combines 
    hands-on design and simulations with hardware integration. A key part of this role is developing the 
    Python-based data workflows to process and analyze the permeation test results, turning raw sensor data 
    into meaningful insights.
  cv: 'static/files/Resume_Abdul Hamid Rather.pdf'
  

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: 'publications'

  - id: 'photos'
    i18n: 'nav.photos'
    name: 'Photos'
    tpl: 'photos.html'
    css: 'photos'

  - id: 'contact'
    i18n: 'nav.contact'
    name: 'Contact'
    tpl: 'contact.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/Germany.png'
  # - locale: 'zh'
  #   flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
